name: Run coding style check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Lint src
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 16.0.3

      - name: Lint libsol
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './libsol'
          extensions: 'h,c'
          clangFormatVersion: 16.0.3
