name: Code style check

on:
  workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Lint src
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 16.0.3

      - name: Lint libsol
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './libsol'
          extensions: 'h,c'
          clangFormatVersion: 16.0.3

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check misspellings
      uses: codespell-project/actions-codespell@v2
      with:
        builtin: clear,rare
        check_filenames: true
        skip: ./libsol/printer_test.c,./tests/Cargo.lock
