name: Misspellings checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check misspellings
      uses: codespell-project/actions-codespell@v2
      with:
        builtin: clear,rare
        check_filenames: true
        skip: ./libsol/printer_test.c,./tests/Cargo.lock
