name: Compilation & tests

on:
  workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: compiled_app_binaries
      run_for_devices: '["nanos", "nanox", "nanosp"]'

  ragger_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: compiled_app_binaries
      test_dir: tests/python
      run_for_devices: '["nanos", "nanox", "nanosp"]'

  job_C_test:
    name: C tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-legacy:latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Build unit tests
        run: make -C libsol
